services:
  server:
    build: .
    pull_policy: build
    restart: always
    ports:
      - ${SERVER_PORT:-7860}:7860
  db:
    image: "mongo:7.0-jammy"
    restart: always
    ports:
      - ${DB_PORT:-}:27017
    volumes:
      - ${DB_VOLUME_DB:-./data/db}:/data/db
      - ${DB_VOLUME_CONFIGDB:-./data/configdb}:/data/configdb
